
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/exchange
    username: root
    password: admin
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
#  level:
#    org.springframework.r2dbc: DEBUG
  file:
    path: log
  logback:
    rolling-policy:
      clean-history-on-start: true
      max-history: 7

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    defaultModelExpandDepth: 4

fileUploadPath: ./files
