
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/exchange
    username: root
    password: admin
  data:
    redis:
      host: 172.10.0.27
      port: 30013
      password: YFKUDeCWD1AL3pGnxHtVoAf3dcwcrTgL

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  show-actuator: true